version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.1.0"

    step:
      - checkout

      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: bundle exec pod install

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
        filter: 
          branches:
            only: master
        requires:
          - build-and-test



